repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.0
    hooks:
      - id: clang-format
        types_or: [c, c++]

  - repo: local
    hooks:
      - id: cppcheck
        name: cppcheck
        entry: cppcheck --enable=all --suppress=missingIncludeSystem src/
        language: system
        types_or: [c, c++]
        pass_filenames: false