[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tmg_hmc"
version = "0.0.2"
authors = [
  { name="Erik A. Bensen", email="ebensen@andrew.cmu.edu" },
]
description = "This package implements exact HMC sampling for truncated multivariate gaussians with quadratic constraints"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "argparse",
    "torch",
    "pickle",
    "scipy"
]
